name: Testing branch for compatibility before merging
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Copy Settings
        run: cp settings.xml ~/.m2/settings.xml
      - name: Run Validation tests - Validate -> Test-Local -> Set-Compatibility -> Test-Compatibility
        run: mvn validate
